language: android
dist: trusty

env:
  global:
    - ANDROID_API=29
    - ANDROID_BUILD_TOOLS=29.0.2
    - ADB_INSTALL_TIMEOUT=5

android:
  components:
    - tools
    - platform-tools-$ANDROID_BUILD_TOOLS
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - '.+'

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_install:
  - chmod +x gradlew
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "build-tools;28.0.3"
  - yes | sdkmanager "platforms;android-28"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

stages:
  - analysis
  - compile
  - test

jobs:
  include:
    - stage: analysis
      script: ./gradlew clean detektCheck lint
    - stage: compile
      install: skip
      before_cache: skip
      script: ./gradlew assemble --stacktrace
    - stage: test
      install: skip
      before_cache: skip
      script: ./gradlew test