language: android
dist: trusty

jdk:
  - openjdk8

env:
  global:
    - ANDROID_API=29
    - ANDROID_BUILD_TOOLS=29.0.2
    - ANDROID_HOME=/usr/local/android-sdk
    - TOOLS=${ANDROID_HOME}/tools
    - PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${TOOLS}:${TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}
    - ADB_INSTALL_TIMEOUT=20
    - EMULATOR_FLAVOR=default
    - EMULATOR_ABI=x86_64
    - EMULATOR_API=21

android:
  components:
    - tools

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - echo 'count=0' > ~/.android/repositories.cfg
  - echo y | sdkmanager "tools" > /dev/null
  - echo y | sdkmanager "platform-tools" > /dev/null
  - echo y | sdkmanager "build-tools;$ANDROID_BUILD_TOOLS" > /dev/null
  - echo y | sdkmanager "platforms;android-$ANDROID_API" > /dev/null

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

stages:
  - develop
  - test

jobs:
  include:
    - stage: develop
      script:
        - ./gradlew clean build
    - stage: test
      install:
        - echo y | sdkmanager "emulator" > /dev/null
        - echo y | sdkmanager "platforms;android-$EMULATOR_API" > /dev/null
        - echo y | sdkmanager "system-images;android-$EMULATOR_API;$EMULATOR_FLAVOR;$EMULATOR_ABI" > /dev/null
        - echo no | avdmanager create avd -f -n test -k "system-images;android-$EMULATOR_API;$EMULATOR_FLAVOR;$EMULATOR_ABI"
        - emulator -avd test -no-accel -no-snapshot -no-window -no-audio -selinux permissive -qemu -m 2048 &
        - android-wait-for-emulator
        - adb shell input keyevent 82 &
      script:
        - ./gradlew connectedCheck